# Generated by Django 2.2.3 on 2019-07-19 19:03

from django.db import migrations, models
# import django_jalali.db.models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taghaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shomare', models.IntegerField(unique=True, verbose_name='شماره تقاضا')),
                ('tarikh', django.db.models.DateField(verbose_name='تاریخ تقاضا')),
                ('sharh', models.CharField(max_length=200, null=True, verbose_name='شرح تقاضا')),
                ('vahed', models.CharField(choices=[(1, 'بهره\u200cبرداری'), (2, 'امور رفاهی'), (3, 'اندازه\u200cگیری و توزیع گاز'), (4, 'حراست'), (5, 'خدمات طرح\u200cها'), (6, 'گازرسانی صنایع')], max_length=200, null=True, verbose_name='شرح تقاضا')),
            ],
            options={
                'verbose_name': 'تقاضا',
                'verbose_name_plural': 'تقاضا ها',
            },
        ),
    ]
