# Generated by Django 2.2.4 on 2019-08-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0006_taghaza_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taghaza',
            name='photo',
        ),
    ]
