# Generated by Django 2.2.4 on 2019-08-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0009_auto_20190811_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taghaza',
            name='image',
            field=models.ImageField(upload_to='static/pics/', verbose_name='تصویر فرم تقاضای کالا (MT26)'),
        ),
    ]
