# Generated by Django 2.2.4 on 2019-08-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0010_auto_20190811_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taghaza',
            name='image',
            field=models.ImageField(height_field='50px', upload_to='static/pics/', verbose_name='تصویر فرم تقاضای کالا (MT26)', width_field='50px'),
        ),
    ]
