# Generated by Django 2.2.4 on 2019-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0012_remove_taghaza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='taghaza',
            name='images',
            field=models.ImageField(default=2, height_field='50px', upload_to='static/pics/', verbose_name='تصویر فرم تقاضای کالا (MT26)', width_field='50px'),
            preserve_default=False,
        ),
    ]
