# Generated by Django 2.2.4 on 2019-08-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0013_taghaza_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taghaza',
            name='images',
        ),
        migrations.AddField(
            model_name='taghaza',
            name='image',
            field=models.ImageField(default=1, upload_to='static/pics/', verbose_name='تصویر فرم تقاضای کالا (MT26)'),
            preserve_default=False,
        ),
    ]
