# Generated by Django 2.2.4 on 2019-08-11 11:17

from django.db import migrations, models
import taghaza.models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0015_auto_20190811_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taghaza',
            name='image',
            field=models.ImageField(upload_to=taghaza.models.Taghaza.user_directory_path, verbose_name='تصویر فرم تقاضای کالا (MT26)'),
        ),
    ]
