# Generated by Django 2.2.4 on 2019-08-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0019_auto_20190818_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taghaza',
            name='vahed',
            field=models.IntegerField(choices=[(0, 'امور قراردادها و پیمانکاران'), (1, 'بهره\u200cبرداری'), (2, 'امور رفاهی'), (3, 'اندازه\u200cگیری و توزیع گاز'), (4, 'حراست'), (5, 'خدمات طرح\u200cها'), (6, 'گازرسانی صنایع'), (7, 'فناوری اطلاعات'), (8, 'امور تدارکات و عملیات کالا'), (9, '(HSE) بهداشت، ایمنی و محیط زیست'), (10, 'روابط عمومی'), (11, 'امور ورزشی'), (0, 'سایر واحدهای ستادی')], verbose_name='واحد متقاضی'),
        ),
    ]
