# Generated by Django 2.2.4 on 2019-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0020_auto_20190818_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taghaza',
            name='sharh',
            field=models.CharField(max_length=500, null=True, verbose_name='شرح تقاضا'),
        ),
        migrations.AlterField(
            model_name='taghaza',
            name='shomare',
            field=models.CharField(max_length=500, unique=True, verbose_name='شماره تقاضا'),
        ),
    ]
