# Generated by Django 2.2.4 on 2019-08-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0021_auto_20190818_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taghaza',
            name='vahed',
            field=models.IntegerField(choices=[(0, 'امورقراردادهاوپیمانکاران'), (1, 'بهره\u200cبرداری'), (2, 'امور رفاهی'), (3, 'اندازه\u200cگیری و توزیع گاز'), (4, 'حراست'), (5, 'خدمات طرح\u200cها'), (6, 'گازرسانی صنایع'), (7, 'فناوری اطلاعات'), (8, 'امورتدارکات وعملیات کالا'), (9, 'HSE اچ اس ای'), (10, 'روابط عمومی'), (11, 'امور ورزشی'), (12, 'سایر واحدهای ستادی')], verbose_name='واحد متقاضی'),
        ),
    ]
