# Generated by Django 2.2.3 on 2019-07-19 19:03

from django.db import migrations, models
import django.db.models.deletion
# import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taghaza', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shomare', models.IntegerField(verbose_name='شماره فاکتور')),
                ('tarikh', django.db.models.DateField(verbose_name='تاریخ فاکتور')),
                ('arzeshe_afzude', models.BooleanField(default=True, verbose_name='ارزش افزوده')),
                ('taghaza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taghaza.Taghaza', verbose_name='تقاضا')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
    ]
