# Generated by Django 2.2.4 on 2019-08-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0010_remove_aghlam_factor'),
        ('factor', '0003_auto_20190804_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='aghlam',
            field=models.ManyToManyField(to='aghlam.Aghlam'),
        ),
    ]
