# Generated by Django 2.2.4 on 2019-08-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0004_factor_aghlam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='aghlam',
        ),
    ]
