# Generated by Django 2.2.4 on 2019-08-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0007_auto_20190812_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='shomare',
            field=models.CharField(max_length=110, null=True, verbose_name='شماره فاکتور'),
        ),
    ]
