# Generated by Django 2.2.4 on 2019-08-18 11:06

from django.db import migrations, models
import factor.models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0009_auto_20190812_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='factor',
            name='image',
            field=models.ImageField(default='static/pics/no-pic.jpg', upload_to=factor.models.Factor.user_directory_path, verbose_name='تصویر فاکتور خرید'),
        ),
    ]
