# Generated by Django 2.2.4 on 2019-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0010_factor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='shomare',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='شماره فاکتور'),
        ),
    ]
