# Generated by Django 2.2.4 on 2019-08-20 16:31

from django.db import migrations, models
import factor.models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0011_auto_20190818_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='aghlam',
            field=models.ManyToManyField(to='aghlam.Aghlam', verbose_name='اقلام خریداری شده'),
        ),
    ]
