# Generated by Django 2.2.3 on 2019-07-19 19:03

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pardaxt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.IntegerField(verbose_name='شماره فیش')),
                ('tarikh', django_jalali.db.models.jDateField(verbose_name='تاریخ فیش')),
                ('hesab', models.IntegerField(verbose_name='شماره حساب')),
                ('name_bank', models.CharField(max_length=15, verbose_name='نام بانک')),
                ('elame_vajh', models.IntegerField(verbose_name='شماره نامه اعلام وجه')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='factor.Factor', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
