# Generated by Django 2.2.4 on 2019-08-03 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kala',
            name='mesc',
            field=models.CharField(default="", max_length=30, verbose_name='MESC'),
            preserve_default=False,
        ),
    ]
