# Generated by Django 2.2.4 on 2019-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0002_kala_mesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='mesc',
            field=models.CharField(max_length=30, verbose_name='شماره طبقه بندی کالا (MESC)'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='vahede_andazegiri',
            field=models.CharField(max_length=15, verbose_name='واحد کالا'),
        ),
    ]
