# Generated by Django 2.2.4 on 2019-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0003_auto_20190811_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kala',
            name='mesc',
            field=models.CharField(max_length=500, verbose_name='شماره طبقه بندی کالا (MESC)'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='sharh',
            field=models.CharField(max_length=500, verbose_name='شرح'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='vahede_andazegiri',
            field=models.CharField(max_length=500, verbose_name='واحد کالا'),
        ),
    ]
