# Generated by Django 2.2.4 on 2019-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0004_auto_20190818_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='kala',
            name='abead',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ابعاد،مشخصات'),
        ),
        migrations.AddField(
            model_name='kala',
            name='estefade',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='مورد استفاده'),
        ),
        migrations.AddField(
            model_name='kala',
            name='jens',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='جنس'),
        ),
        migrations.AddField(
            model_name='kala',
            name='noe',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='نوع'),
        ),
        migrations.AddField(
            model_name='kala',
            name='rang',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='kala',
            name='shekl',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شکل'),
        ),
        migrations.AlterField(
            model_name='kala',
            name='sharh',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شرح'),
        ),
    ]
