# Generated by Django 2.2.4 on 2019-08-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0006_auto_20190820_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='jens',
        ),
        migrations.RemoveField(
            model_name='kala',
            name='rang',
        ),
        migrations.RemoveField(
            model_name='kala',
            name='shekl',
        ),
        migrations.AlterField(
            model_name='kala',
            name='abead',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ابعاد'),
        ),
    ]
