# Generated by Django 2.2.4 on 2019-08-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0007_auto_20190820_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='abead',
        ),
    ]
