# Generated by Django 2.2.4 on 2019-08-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala', '0008_remove_kala_abead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kala',
            name='noe',
        ),
        migrations.AlterField(
            model_name='kala',
            name='sharh',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شرح کالا'),
        ),
    ]
