# Generated by Django 2.2.2 on 2019-07-24 05:34

from django.db import migrations, models
import django.db.models.deletion
# import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('resid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resid',
            name='nam',
        ),
        migrations.AddField(
            model_name='resid',
            name='tarikh',
            field=django.db.models.DateField(verbose_name='تاریخ رسید', ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resid',
            name='taghaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='taghaza.Taghaza', verbose_name='تقاضا'),
        ),
    ]
