# Generated by Django 2.2.2 on 2019-07-24 05:39

from django.db import migrations
# import django_jalali.db.models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resid', '0002_auto_20190724_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resid',
            name='tarikh',
            field=django.db.models.DateField(null=True, verbose_name='تاریخ رسید'),
        ),
    ]
