# Generated by Django 2.2.4 on 2019-08-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resid', '0004_resid_shomare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resid',
            name='tarikh',
            field=models.DateField(null=True, verbose_name='تاریخ رسید'),
        ),
    ]
