# Generated by Django 2.2.3 on 2019-07-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aghlam',
            name='makhs',
        ),
    ]
