# Generated by Django 2.2.2 on 2019-07-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0003_auto_20190721_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aghlam',
            name='sherkat',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sherkat.Sherkat', verbose_name='تامین کننده'),
            preserve_default=False,
        ),
    ]
