# Generated by Django 2.2.2 on 2019-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0006_auto_20190721_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='aghlam',
            name='external',
            field=models.BooleanField(default=1, verbose_name='خارجی'),
            preserve_default=False,
        ),
    ]
