# Generated by Django 2.2.4 on 2019-08-06 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taghaza', '0005_auto_20190804_0605'),
        ('aghlam', '0007_aghlam_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='aghlam',
            name='taghaza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_query_name='taghaza', to='taghaza.Taghaza', verbose_name='تقاضا'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aghlam',
            name='external',
            field=models.BooleanField(blank=True, null=True, verbose_name='خارجی'),
        ),
        migrations.AlterField(
            model_name='aghlam',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factor.Factor', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='aghlam',
            name='mablagh',
            field=models.IntegerField(blank=True, null=True, verbose_name='مبلغ واحد'),
        ),
    ]
