# Generated by Django 2.2.4 on 2019-08-06 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0009_auto_20190806_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aghlam',
            name='factor',
        ),
    ]
