# Generated by Django 2.2.4 on 2019-08-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0005_remove_factor_aghlam'),
        ('aghlam', '0010_remove_aghlam_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aghlam',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factor.Factor', verbose_name='فاکتور'),
        ),
    ]
