# Generated by Django 2.2.4 on 2019-08-10 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0011_aghlam_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aghlam',
            name='factor',
        ),
    ]
