# Generated by Django 2.2.4 on 2019-08-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0012_remove_aghlam_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aghlam',
            name='taghaza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='taghaza', to='taghaza.Taghaza', verbose_name='تقاضا'),
        ),
    ]
