# Generated by Django 2.2.4 on 2019-08-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0013_auto_20190812_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aghlam',
            name='taghaza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='taghaza', to='taghaza.Taghaza', verbose_name='تقاضا'),
            preserve_default=False,
        ),
    ]
