# Generated by Django 2.2.4 on 2019-08-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aghlam', '0014_auto_20190812_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aghlam',
            name='external',
            field=models.BooleanField(default=False, verbose_name='خارجی'),
        ),
    ]
