# Generated by Django 2.2.4 on 2019-08-03 10:46

from django.db import migrations, models
import django.utils.timezone
# import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasfie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasfie',
            name='mablagh',
            field=models.IntegerField(verbose_name='تاریخ تسویه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasfie',
            name='noe',
            field=models.IntegerField(choices=[(0, 'تنخواه\u200cگردان'), (1, 'ازمحل\u200cتقاضا'), (2, 'علی\u200cالحساب')], verbose_name='تاریخ تسویه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasfie',
            name='shomare',
            field=models.CharField(max_length=15, verbose_name='نام بانک'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasfie',
            name='tarikh',
            field=django.db.models.DateField( verbose_name='تاریخ تسویه'),
            preserve_default=False,
        ),
    ]
