# Generated by Django 2.2.4 on 2019-08-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasfie', '0003_auto_20190804_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasfie',
            name='mablagh',
            field=models.IntegerField(verbose_name='مبلغ تسویه'),
        ),
        migrations.AlterField(
            model_name='tasfie',
            name='noe',
            field=models.IntegerField(choices=[(0, 'تنخواه\u200cگردان'), (1, 'ازمحل\u200cتقاضا'), (2, 'علی\u200cالحساب')], verbose_name='نوع تسویه'),
        ),
    ]
