# Generated by Django 2.2.4 on 2019-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasfie', '0004_auto_20190818_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasfie',
            name='shomare',
            field=models.CharField(max_length=500, verbose_name='نام بانک'),
        ),
    ]
