# Generated by Django 2.2.4 on 2019-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasfie', '0005_auto_20190818_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasfie',
            name='bank',
            field=models.CharField(default=1, max_length=500, verbose_name='نام بانک'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasfie',
            name='shomare',
            field=models.CharField(max_length=500, verbose_name='شماره تسویه'),
        ),
    ]
