# Generated by Django 2.2.4 on 2019-08-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherkat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sherkat',
            name='nam',
            field=models.CharField(max_length=500, verbose_name='نام شرکت'),
        ),
    ]
