"""
Django settings for chortke project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from django.conf.locale.fa import formats as fa_formats

USE_I18N = True
USE_L10N = True
USE_I18N = True
TIME_ZONE = 'Iran'
LANGUAGE_CODE = 'fa' # or en-nz? both don't work
DATE_INPUT_FORMATS = ['%Y/%m/%d']
DATETIME_INPUT_FORMATS = ['%Y/%m/%d %H:%M:%S', '%Y/%m/%d %H:%M:%S']

fa_formats.DATE_FORMAT = 'Y/m/d'
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    'static',
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '0@sm#g2!uu52mu@a(8r1or*q^@_esrjzh52o^l4r=&--y%r&^s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','localhost', '[::1]']

# Application definition

INSTALLED_APPS = [
    # 'admin_totals',
    'django_admin_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'import_export',
    'admin_reorder',
    'nested_admin',
    'rangefilter',
    'factor.apps.FactorConfig',
    # 'pardaxt.apps.PardaxtConfig',
    'resid.apps.ResidConfig',
    # 'sefaresh.apps.SefareshConfig',
    'sherkat.apps.SherkatConfig',
    'tasfie.apps.TasfieConfig',
    'taghaza.apps.TaghazaConfig',
    'kala.apps.KalaConfig',
    'salemali.apps.SalemaliConfig',
    'aghlam.apps.AghlamConfig',

]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'admin_reorder.middleware.ModelAdminReorder',


]

ROOT_URLCONF = 'chortke.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chortke.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

ADMIN_REORDER = (
    # Reorder app models
    {'app': 'taghaza','label': 'منوی اصلی ورود اطلاعات:', 'models': ('taghaza.Taghaza', 'factor.Factor','resid.Resid', 'tasfie.Tasfie','salemali.Salemali', )},
    {'app': 'sherkat','label': 'آرشیو اقلام، کالاها، شرکت ها:', 'models': ('sherkat.Sherkat', 'aghlam.Aghlam', 'kala.Kala', )},
    {'app': 'auth', 'label': 'تنظیمات کاربران و گروه ها:', 'models': ('auth.User', 'auth.Group', )},

)

FAKER_LOCALE = 'fa'  # settings.LANGUAGE_CODE is loaded
FAKER_PROVIDERS = None  # faker.DEFAULT_PROVIDERS is loaded (all)
